### ISSUE TITLE
Differentiate between minor and major releases

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/scikit-hep.github.io#199]
In PR #193 Scikit-HEP got a news page! :tada: At the moment all the releases are noted as "major" even if they are "minor" releases in SemVer.

Example: `boost-histogram` `v1.0.0` and `pyhf` `v0.6.0` are both described as "major"

https://github.com/scikit-hep/scikit-hep.github.io/blob/e91e0c3de2f026f8c907963df370f62128322752/pages/news.md?plain=1#L45-L53

Should we adopt SemVer conventions and change the SemVer minor releases to be described as "minor"?

**Comment by eduardo-rodrigues** [comment]
Mea culpa. I can explain the rationale behind the wording:
I put "major releases e.g. in boost-histogram v1.0.0 and pyhf v0.6.0 because they effectively are. I mean, boost-histogram v1.0.0 clearly is and pyhf v0.6.0 effectively is because you're not on 1.x yet but the 0.x.0 are, I believe, the important "milestones." If you dislike we can simply remove the word "major" almost everywhere since the main piece of info if for sure the package name + "important" release. Would you prefer? I undestand your point. I hope you see my reasoning.

We do follow SemVer pretty much everywhere as far as I know.

**Comment by eduardo-rodrigues** [comment]
I'm happy to create a follow-up MR.

**Comment by matthewfeickert** [comment]
> If you dislike we can simply remove the word "major" almost everywhere since the main piece of info if for sure the package name + "important" release.

This is probably fine. I don't see any problem differentiating between major, minor, patch releases as the libraries are already doing that in their release notes but I also don't see any problem with just going with what you implemented in PR #202.
