### ISSUE TITLE
Reduce intro text on main page

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/scikit-hep.github.io#41]
The current intro text is quite long; if you have a smaller screen, you may not even know that there is a list of packages below, which is one of the most useful parts of the main page. I recommend shortening it quite a bit, and maybe even moving most of it to a separate "about" page. Thoughts, especially @eduardo-rodrigues ?

**Comment by eduardo-rodrigues** [comment]
You mean this
"
The Scikit-HEP project is a community-driven and community-oriented project with the aim of providing Particle Physics at large with an ecosystem for data analysis in Python. The project started in Autumn 2016 and is in full swing.
It is not just about providing core and common tools for the community. It is also about improving the interoperability between HEP tools and the scientific ecosystem in Python, and about improving on discoverability of utility packages and projects.
For what concerns the project grand structure, it should be seen as a toolset rather than a toolkit. The project defines a set of five pillars, which are seen to embrace all major topics involved in a physicist's work. These are:
"
?
I find this as short as it gets, actually: to make it useful. It's just 3 sentences worth a 30-sec read. Less will make it useless, I fear.

Looking again at the homepage, now that many logos have been added: the issue I do see now is that I get overwhelmed by many badges and big-ish logos and totally fail to see the structure of the project. The idea of this page was to give an overview of the project and what's in it. In that sense I actually found it easier to grasp the grand picture when we had sections and simple listings. After all, if you are looking at the website and reading about the project, changes are that you will want to follow links to the repositories of certain packages that trigger your interest; you won't immediately go and click on the PyPI release pages I would imagine.

So, a separate page for "Project packages" could be added just above the left menu item "Affiliated packages". It would have the content of the second part of the homepage. And we would make the homepage simple again, for a project overview. How does that sound?

**Comment by henryiii** [comment]
What would someone looking at scikit-hep for the first time need to see? The listing of the five pillars, for example, seems to be superfluous when you can just look below at the actual divisions and packages. This was originally meant to be sort of a plan because it didn't exist yet. Now much of it does.

I don't think that showing a large amount of text to a new visitor is ideal. Look at other websites. Numfocus has one sentence and a read more button. Below that they have an engagement strip, then they have a scrolling project logos banner. No text about each project, just logos.

Scikit-learn has four bullet points, then they have pictures with "examples" buttons.

I think we should be reducing the text and increasing the prominence of the logos, not the other way around. Maybe 1-2 sentences and a "Read more" button?

**Comment by henryiii** [comment]
(We can fix the visual design later, where the headings are more prominent and the packages are more like tiles. Also having a packages page is not a bad idea.)

**Comment by eduardo-rodrigues** [comment]
Following up from our chat viva voce. So we agreed to:
- Get the main page shorter and move some details to an "About" page to be added to the left-hand menu.
- Add to the menu a page on "Project packages", to complement the "Affiliated packages" page.
- Try and get everyone to prepare logos for their packages.

I'm missing something but this is a step forward :-)-

**Comment by henryiii** [comment]
Closed in #49.
